/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_OQSEERR_H
# define HEADER_OQSEERR_H

# define OQSEerr(f, r) ERR_OQSE_error((f), (r), OPENSSL_FILE, OPENSSL_LINE)


# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_OQSE_strings(void);
void ERR_unload_OQSE_strings(void);
void ERR_OQSE_error(int function, int reason, const char *file, int line);
# ifdef  __cplusplus
}
# endif

/*
 * OQSE function codes.
 */
# define OQSE_F_OQSE_ASN1_BITS                            100
# define OQSE_F_OQSE_ASN1_ITEM_SIGN                       101
# define OQSE_F_OQSE_ASN1_ITEM_VERIFY                     102
# define OQSE_F_OQSE_ASN1_PRIV_DECODE                     103
# define OQSE_F_OQSE_ASN1_PRIV_ENCODE                     104
# define OQSE_F_OQSE_ASN1_PUB_DECODE                      105
# define OQSE_F_OQSE_ASN1_PUB_ENCODE                      106
# define OQSE_F_OQSE_ASN1_SECURITY_BITS                   107
# define OQSE_F_OQSE_BIND_HELPER                          108
# define OQSE_F_OQSE_GET_SECURITY_BITS                    109
# define OQSE_F_OQSE_KEY_INIT                             110
# define OQSE_F_OQSE_NID2OQS                              111
# define OQSE_F_OQSE_PKEY_AMETHS                          112
# define OQSE_F_OQSE_PKEY_PMETHS                          113
# define OQSE_F_OQSE_PMETH_DIGESTSIGN                     114
# define OQSE_F_OQSE_PMETH_DIGESTVERIFY                   115
# define OQSE_F_OQSE_PMETH_KEYGEN                         116
# define OQSE_F_OQSE_PMETH_SIGN                           117
# define OQSE_F_OQSE_PMETH_VERIFY                         118
# define OQSE_F_OQSE_REGISTER_NID                         119
# define OQSE_F_OQSE_REGISTER_NIDS                        120
# define OQSE_F_OQSE_SIZE                                 121

/*
 * OQSE reason codes.
 */
# define OQSE_R_ALREADY_REGISTERED                        100
# define OQSE_R_BAD_INIT                                  101
# define OQSE_R_BAD_NID                                   102
# define OQSE_R_CALLOC_FAILED                             103
# define OQSE_R_ENGINE_BIND_AMETH_FAILED                  104
# define OQSE_R_ENGINE_BIND_INIT_FAILED                   105
# define OQSE_R_ENGINE_BIND_NAME_FAILED                   106
# define OQSE_R_ENGINE_BIND_PMETH_FAILED                  107
# define OQSE_R_ENGINE_BIND_REGISTER_AMETH_FAILED         108
# define OQSE_R_ENGINE_BIND_REGISTER_NIDS_FAILED          109
# define OQSE_R_ENGINE_BIND_REGISTER_PMETH_FAILED         110
# define OQSE_R_ENGINE_BIND_SET_DESTROY_FAILED            111
# define OQSE_R_ENGINE_BIND_SET_FAILED                    112
# define OQSE_R_ENGINE_BIND_SET_FINISH_FAILED             113
# define OQSE_R_FAILED_KEYGEN                             114
# define OQSE_R_FATAL                                     115
# define OQSE_R_MALLOC_FAIL                               116
# define OQSE_R_MALLOC_FAILED                             117
# define OQSE_R_MALLOC_FAILURE                            118
# define OQSE_R_NID_NOT_FOUND                             119
# define OQSE_R_NID_UNDEF                                 120
# define OQSE_R_NO_ALGOR                                  121
# define OQSE_R_NO_ALG_DATA                               122
# define OQSE_R_NO_DATA                                   123
# define OQSE_R_NO_KEY                                    124
# define OQSE_R_OBJ_CREATE_FAILED                         125
# define OQSE_R_OBJ_RETRIEVE_FAILED                       126
# define OQSE_R_QSE_NEW_FAILED                            127
# define OQSE_R_SIGN_NEW_FAILED                           128
# define OQSE_R_UNKNOWN_NIST_LEVEL                        129

#endif
